[build]
  # 无需构建命令，因为是纯静态文件
  command = ""
  
  # 发布目录就是根目录
  publish = "."

[[redirects]]
  # 处理客户端路由，确保直接访问子页面时不会404
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# 为登录页面设置特殊处理
[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

# 设置默认的安全头
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 为 JavaScript 文件设置正确的 MIME 类型
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

# 为 CSS 文件设置正确的 MIME 类型
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
